import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1 className={styles.title}>MDIA 2109 Class 8 - UseEffect & Carousel </h1>
          <h2 className={styles.desc}>Assignment 2</h2>
        </div>
        <div className={styles.categoriesContainer}>
          <Link href="/useEffectOne">useEffect One</Link>
          <Link href="/useEffectTwo">useEffect Two</Link>
          <Link href="/useEffectThree">UseEffect Three</Link>
          <Link href="/carouselPage">Carousel Page</Link>
        </div> 
      </main>
    </>
  )
}
